# Generated by Django 4.2.7 on 2026-02-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_password_protected',
            field=models.BooleanField(default=False, verbose_name='Захищена паролем'),
        ),
        migrations.AddField(
            model_name='note',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Хеш паролю'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-updated_at'], name='notes_user_id_8a4da1_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_password_protected'], name='notes_is_pass_5753da_idx'),
        ),
    ]
