# Generated by Django 4.2.7 on 2026-02-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_is_password_protected_note_password_hash_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='note',
            name='notes_user_id_8a4da1_idx',
        ),
        migrations.RemoveIndex(
            model_name='note',
            name='notes_is_pass_5753da_idx',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_password_protected',
        ),
        migrations.RemoveField(
            model_name='note',
            name='password_hash',
        ),
    ]
