# Generated by Django 4.2.7 on 2026-02-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_notes_user_id_8a4da1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_password_protected',
            field=models.BooleanField(default=False, verbose_name='Захищена паролем'),
        ),
        migrations.AddField(
            model_name='note',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гешований пароль'),
        ),
    ]
